site:
  title: Entropy
  start_page: Entropy::index.adoc 
#  url: https://...
content:
  sources: 
  - url: .
    branches: "master"
    start_path: .
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  clean: true
  dir: ./build/out